### PR TITLE
Update msgp v1.1.9

### PR DESCRIPTION
**Pull request by r0mdau**
Problem: version conflict at runtime, see this comment https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29413#issuecomment-1987241795

Goal: use this library in a [fluentforward](https://github.com/r0mdau/fluentforwardexporter) Opentelemetry exporter and merge this exporter to the [opentelemetery-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main) repository.

Version used in opentelemetry-collector-contrib [go.sum link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/go.sum#L1562).

tinylib/msgp changes: https://github.com/tinylib/msgp/releases/tag/v1.1.9

### CODE REVIEW

**Comment by r0mdau** [comment]
@mirko-lazarevic let me know if it makes sense for the project.

**Comment by mirko-lazarevic** [comment]
Hi @r0mdau , apologise for not responding sooner. Yes, this makes sense. I'm going to test it ASAP, if everything is working as expected, I'll merge it.

**Comment by r0mdau** [comment]
Sounds good, I ran unit tests successfully but my testing scope stopped here, I am glad you test it also.

**Review by mirko-lazarevic — APPROVED** [review]
This looks good. I performed manual tests, everything is working as expected.

**Comment by r0mdau** [comment]
Thanks @mirko-lazarevic

**Pull request merged**
